name: Build - Staging

on:
  push:
    branches:
    - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Publish Docker Container
      uses: elgohr/Publish-Docker-Github-Action@1.14
      with:
        name: rangerdigital/tohru-parser
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
