name: Build / Deploy - Production

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        
    - name: Build App
      run: |
        npm install
        npm run build
      env:
        CI: true

    - name: Install Rsync
      run: |
        sudo apt update
        sudo apt install rsync

    - name: RSync To Sylvanas
      run: |
        echo ${{ secrets.SSH_KEY }} > key
        rsync -Pav --delete -e "ssh -i key" dist/* ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOSTNAME }}:/var/www/tohru.bednarski.dev/

