name: Deploy Frontend

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Build App
        run: |
          npm install
          npm run build
        env:
          CI: true

      - name: Install Rsync
        run: |
          sudo apt update
          sudo apt install rsync

      - name: Prepare SSH Agent
        uses: webfactory/ssh-agent@master
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: RSync To Sylvanas
        run: |
          rsync -Pav --rsync-path="sudo rsync" --delete -e "ssh -o StrictHostKeyChecking=no" dist/* ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOSTNAME }}:/var/www/tohru.bednarski.dev/
